[[redirects]]
  from = "https://app.soakmont.com/*"
  to = "https://app.soakverse.io/:splat"
  status = 301
  force = true
  
[[redirects]]
  from = "https://app.soakmont.com"
  to = "https://app.soakverse.io"
  status = 301
  force = true